In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_json("E:\Job_Market_Analysis\Kaggle_data\Tech_job_Market_in_india\marketing_sample_for_indeed_co_in-indeed_co_in_job_data__20211001_20211231__30k_data.ldjson\marketing_sample_for_indeed_co_in-indeed_co_in_job_data__20211001_20211231__30k_data.ldjson", lines = True)

<>:1: SyntaxWarning: invalid escape sequence '\J'
<>:1: SyntaxWarning: invalid escape sequence '\J'
C:\Users\Gourav Banjara\AppData\Local\Temp\ipykernel_11652\700025316.py:1: SyntaxWarning: invalid escape sequence '\J'
  df = pd.read_json("E:\Job_Market_Analysis\Kaggle_data\Tech_job_Market_in_india\marketing_sample_for_indeed_co_in-indeed_co_in_job_data__20211001_20211231__30k_data.ldjson\marketing_sample_for_indeed_co_in-indeed_co_in_job_data__20211001_20211231__30k_data.ldjson", lines = True)

In [5]:
df.head()
df.columns

Index(['uniq_id', 'crawl_timestamp', 'url', 'job_title', 'category',
       'company_name', 'logo_url', 'city', 'state', 'country', 'post_date',
       'job_description', 'job_type', 'job_board', 'geo', 'job_post_lang',
       'html_job_description', 'inferred_iso2_lang_code', 'is_remote',
       'test1_cities', 'test1_states', 'test1_countries', 'site_name',
       'domain', 'postdate_yyyymmdd', 'predicted_language',
       'inferred_iso3_lang_code', 'test1_inferred_city',
       'test1_inferred_state', 'test1_inferred_country', 'inferred_city',
       'inferred_state', 'inferred_country', 'has_expired',
       'last_expiry_check_date', 'latest_expiry_check_date', 'dataset',
       'postdate_in_indexname_format', 'segment_name', 'run_forced',
       'job_desc_char_count', 'ijp_reprocessed_flag_1',
       'ijp_reprocessed_flag_2', 'ijp_reprocessed_flag_3', 'fitness_score',
       'company_description', 'duplicate_status', 'test_contact_email',
       'contact_email'],
      dtype='object')

In [7]:
df = pd.DataFrame({'timestamp':df['crawl_timestamp'], 'Job_Title':df['job_title'], 'category':df['category'],'city':df['city'],
                            'post_date':df['post_date'],'job_description':df['job_description'],'job_type':df['job_type'],'job_board':df['job_board'],
                            'postdate_yyyymmdd':df['postdate_yyyymmdd'],'has_expired':df['has_expired'],'dataset':df['dataset']})

In [8]:
df = df[df['category'].isin(['IT', 'Computer','Engineering','Internet'])]
df.reset_index(inplace=True, drop = True)
df.index +=1

In [9]:
df['Job_Title'][3430:3481]
# df['Job_Title'].nunique()

3431                              Sr. Front End Developer
3432                                        iOS Developer
3433                                       Staff Engineer
3434                                         IT Executive
3435                                    Software Engineer
3436                       SoC Design Engg - LOGIC Design
3437                                    Marketing Manager
3438    Senior PHP Full Stack Developer (Symfony/Vue.j...
3439       Team Leader(Software Developer in.Net project)
3440                                    Sr. SEO Executive
3441                                        iOS Developer
3442    Software Engineer / Senior software Engineer -...
3443                  Looking For Accessibility Developer
3444                                              Trainee
3445                                    Android Developer
3446                       Azure Cloud Solution Architect
3447          Opening for Assistant Project Lead - (Java)
3448                        JAVA Developer-drive 27th Nov
3449                               Android/iOS Internship
3450                    Print Project Manager Contractual
3451                       Manager I - Project Management
3452                                     Software Trainer
3453                           Senior Software Specialist
3454                               C++ Embedded Developer
3455                                         DGM- P2P,R2R
3456                                    Node js developer
3457                 SaT_TSE Custimer_Senior Analyst_Core
3458    Developer - Cloud Development and ABAP-NGAP Stack
3459                       Business Development Executive
3460                                        iOS Developer
3461                                Cloud DevOps Engineer
3462                                     Business Analyst
3463                          Digital Marketing Executive
3464                                ASP.NET MVC Developer
3465                                  Data Entry Operator
3466                            DG Process Developer - AP
3467                                     Business Analyst
3468                        Android Application Developer
3469                                  Software Engineer I
3470                              Staff Software Engineer
3471                         Sr. Web Designer & Developer
3472                        Software Development Engineer
3473                        Senior Engineer, SAP Security
3474                                 Mid Senior Architect
3475                                        PHP Developer
3476                              Backend Developer- Java
3477                                    ASP.NET Developer
3478                   Silicon Design Engineer 2 (117747)
3479               Senior PreSi Verif/Validation Engineer
3480                            Manager - Territory Sales
3481                       Professional Services Engineer
Name: Job_Title, dtype: object

In [10]:
role_map = {    'Business Analyst':['Business Analyst','BI Analyst'],
                'Data Analyst' :   ['Data_Analyst','Marketing Analyst','Reporting Analyst','Product Analyst',
                                'Junior Data Analyst', 'Data Analyst Junior','Data Visualization Analyst','Analyst'],
                'Data Scientist':['Data Scientist','Junior Data Scientist','Data Science Analyst'],
                'Operation Analyst':['Operations Analyst'],
                'Financial Analyst':['Financial Analyst'],
                'Data Engineer':['Data Engineer','Database Engineer','Database'],  
                'SQL Developer':['SQL Developer','SQl'],
                'Software Engineer':['Software Engineer','Software'],
                'Web Developer':['Web Developer', 'Web Development', 'WordPress', 'Full Stack'],
                '.Net Developer': ['.Net Developer','Dot Net Developer' ] , 
                'IOS Developer':['IOS Developer','IOS'],
                'Python Developer':['Python Developer', 'Python'],
                'Java Developer':['Java Developer','Java'],
                'C/C++ Developer':['C/C++_Developer','C/C++','C++'],
                'Javascript Developer':['Javascript_Developer','Javascript','React JS','Reactjs','Nodejs','Node JS', 'JS Developer'],
                'Technical Support_Engineer' : ['Technical_Support_Engineer','Technical', 'Tech Support', 'Technical Support'],
                'Application Developer':['Application_Developer'],
                'Frontend Developer': ['Frontend'],
                'Backend Developer':['Backend'],
                'Mechenical Engineer':['Mechenical'],
                'Civil Engineer' : ['Civil'],
                'PHP Developer':['PHP'],
                'Android Developer':['Android'],
                'Digital Marketing':['Digital Marketing','SEO','Search Engine Optimization'],
                'Cloud Engineer':['Cloud Enginner','Azure','AWS'],
                'Testing Developer': [ 'Testing'],
                'UI/UX Engineer':['UI','UX','UI/UX'],
                'Game Developer':['Game']
                }

In [11]:
def map_job_role(title):
    title = str(title).lower()
    for role, patterns in role_map.items():
        for pattern in patterns:
            if pattern.lower() in title:
                return role
    return None

df['Job_Role'] = df['Job_Title'].apply(map_job_role)

In [12]:
df.loc[df['Job_Role'].isnull()]
df = df[df['Job_Role'].notnull()]

In [13]:
df['Job_Role'].unique()
df.head()
df = df.drop(columns= 'timestamp')

In [14]:
df.head(20)
df.reset_index(inplace=True, drop = True)
df.index += 1

In [15]:
df.groupby('Job_Role').count()
df

,Job_Title,category,city,post_date,job_description,job_type,job_board,postdate_yyyymmdd,has_expired,dataset,Job_Role
1,Technical Project Manager,Computer,Vadodara,2021-11-11,"Rishabh Software(CMMi Level 3), an India based...",Full-time,indeed,20211111,false,[job_board],Technical Support_Engineer
2,Civil Engineer,Engineering,Nagpur,2021-12-05,Greetings Urgently required: Civil Engineer Ed...,Full-time,indeed,20211205,false,[job_board],Civil Engineer
3,"Software Engineer| Net, MVC, ASP.Net and My SQL",Computer,Pune,2021-12-15,Welcome to Allscripts! Our Mission is to be th...,Full-time,indeed,20211215,false,[job_board],SQL Developer
4,Sr. PHP Developer(Laravel),IT,Gurgaon,2021-12-27,"About the company: ContactPoint 360, Inc. is a...",Full-time,indeed,20211227,false,[job_board],PHP Developer
5,Application Developer: Java Full Stack,IT,Bengaluru,2021-11-13,"Introduction As an Application Developer, you ...",Full-time,indeed,20211113,false,[job_board],Web Developer
...,...,...,...,...,...,...,...,...,...,...,...
2807,"Lead Engineer, Software Engineering",Engineering,Hyderabad,2021-11-21,"As the Lead Engineer, Software Engineering, yo...",Full-time,indeed,20211121,false,[job_board],Software Engineer
2808,Java Developer,IT,Pune,2021-12-23,JAVA DEVELOPER 3 to 5 yrs of work experience O...,Full-time|Temporary|Contract,indeed,20211223,false,[job_board],Java Developer
2809,Frontend Developer,IT,J P Nagar,2021-11-18,Innovary is seeking an experienced Front–end d...,Full-time,indeed,20211118,false,[job_board],Frontend Developer
2810,Android Developer_Digibank,IT,Telangana,2021-11-18,Business Function Group Technology and Operati...,Full-time,indeed,20211118,false,[job_board],Android Developer
2811,Performance Testing Trainer,IT,Hyderabad,2021-12-04,Looking for a Performance test engineer to tra...,Part-time|Temporary|Contract,indeed,20211204,false,[job_board],Testing Developer

In [16]:
df.to_excel('indeed_30K_Tech_jobs_data.xlsx', index=0)